name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      # Install the newman command line utility and also install the html extra reporterr
      - name: Install newman
        run: |
          npm install -g newman

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run TesteAPI.json
          
      - name: Run POSTMAN collection Critical
        run: |
          newman run TesteAPICriticos.json --delay-request 100

