name: Newman Run

on:
  pull_request:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Run API Tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: TesteAPI.json
