name: Newman Run

on:
  pull_request:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@main
        with:
          collection: TesteAPI.json
